### ISSUE TITLE
How can I reset "gap_limit" in my bitcoin payment?

### ISSUE THREAD

**Issue by Thinkdiff** [blockchain/api-v1-client-node#30] opened 2017-05-05 14:14 UTC
My xpub "gap_limit" goes "21" and still is "21". How can I reset it? and how can I reset it during application working if my client tries to send a huge invalid request for increasing my gap_limit?

**Comment by jtormey** [comment] 2017-05-05 18:07
To reset the gap limit you must send bitcoin to one of the recent addresses generated by the API. It's recommended to be careful with how often new addresses are generated, otherwise it's possible that many empty addresses will be made and the gap limit will be reached.

To increase your gap limit you can specify a `gap_limit` parameter, although this isn't supported in the node client and should only be used by those who fully understand the idea of a "gap limit" in bitcoin ([docs](https://blockchain.info/api/api_receive)). Our servers will not watch more than 20 unused addresses in a row.

**Comment by Thinkdiff** [comment] 2017-05-05 18:11
You mean It`s better that I keep each generated address in the database and for requests, if I had any generated address in DB, I should send amount and transaction to that existing address and if not, trying to create now request and transaction?

**Comment by jtormey** [comment] 2017-05-05 18:17
Once an address is given to a client, it shouldn't be given to another client, even if it still hasn't been used (for security / privacy). What is recommended is to only generate a new address when you are sure it is going to be used, or where there will likely be a low drop-off rate.

For example, generating and displaying a new address on the home page of a website is not good, because many empty addresses will be created (it's unlikely someone who goes to the home page will send bitcoin to the address generated).

A good place to generate a new address would be, for example, at the final step of an online checkout process, since there is a high likelihood the user has already committed to paying.

**Closed** 2017-06-19 14:56 UTC

**Comment by komalnicm** [comment] 2017-12-08 16:33
i have my own wallet for cryprocurrency. so i used blockchain API for bitcoin transcation. i use api key and xpub so i can trasnfer btc to wallet. but in, testing phase in trouble for limitation of Addresses generated. Gap limit to access more than 20 addresses. how to generate new addresses after gap limit? plz give me positive feedback for blockchain integation.

**Comment by komalnicm** [comment] 2017-12-08 16:35
How to delete unused addresses in blockchain wallet? so i can generate new addresses for new clients

**Comment by icryptix** [comment] 2017-12-21 05:05
I have the same question. How can we delete the old unused addresses in Blockchain? Is there a way to delete them programmatically also?

**Comment by jongrover** [comment] 2018-01-13 00:54
@jtormey I know this is a closed thread, but I placed my button to "generate a new address as the final step of an online checkout process" as you mentioned and "not on my homepage", but people are very curious by nature and still will click the button and create unused addresses.
As @icryptix and @komalnicm requested it would be nice to have a way to programatically remove unused addresses that are created by curious/foolish users. Otherwise we are betting on the user to not max out our gap-limit which is total uncertainty and perhaps force to personally send bitcoin to those addresses ourselves. Has anyone come across a solution to this or found an API that can help? Thanks in advance.

**Comment by stan-asiegbu** [comment] 2018-02-08 03:13
I totally agree with @jongrover. It's a closed thread but something should be done about this. It's really really important.

**Comment by jongrover** [comment] 2018-02-09 17:12
@stan-asiegbu I did find some paid services that address this such as Blockonomics API that charges a small fee but will automatically send a small amount of bitcoin to unused addresses which fixes the GAP limit issue. They explain it in their FAQ here: https://www.blockonomics.co/views/faqs.html
Alternately, [This reddit post](https://www.reddit.com/r/Bitcoin/comments/5jfyv4/technical_address_gap_limit_a_problem_with/) suggested running your own full node to accept payments.
I still wish blockchain API would provide a native solution without using third-party api.

**Comment by stan-asiegbu** [comment] 2018-03-27 00:38
Sorry it's as late as this. I just saw your message. I really appreciate
your help. I already looked at blockonomics too and think I'd finally go
for it. Thanks

**Comment by JustPerfection** [comment] 2018-05-20 23:56
@jtormey 
Maybe I'm late here, but you closed this topic just based on this solution: hope!

There are some questions:

> Once an address is given to a client, it shouldn't be given to another client, even if it still hasn't been used (for security / privacy).

So the address should be the reason for gap limit forever?
Some people suggesting sending low amount of bitcoin to the address and then it will be free! This is not really a good solution to me. how about when I send the bitcoin and at the same time that address receiving the real amount that the client sent (just with delay)!

see this link:
https://bitcoin.stackexchange.com/questions/74410/blockchain-address-gap-limit-solution

So this shouldn't be a solution when we shouldn't give the address to another client.

> A good place to generate a new address would be, for example, at the final step of an online checkout process, since there is a high likelihood the user has already committed to paying. Therefore, most addresses will receive bitcoin and it's less likely you'll ever reach the gap limit.

How about a curious ones? 20 clients go to the checkout page and don't pay and simply close the page. How about that? lets say 1000 clients do that and we have 1000 gap limit. how about 1001? We still have gap limit.

I found creating new xpub and switching to it, is not a good solution either. It has limit for each wallet and we need to create new wallet when we reached to the limit.

**Comment by jtormey** [comment] 2018-05-21 15:15
I realize the 20 address gap limit does not fit everyone's use case. For that reason, I've added an options parameter to the `Receive` constructor where you can specify a custom gap limit, this can be set as high as you need it to be. [See documentation](https://github.com/blockchain/api-v1-client-node/tree/master/Receive#usage).

*Note that the default limit is there as a safeguard, so to make sure everyone understands the issues involved with raising the gap limit, I'll include a warning here:*

⚠️**WARNING**⚠️

**Using a gap limit above 20 goes against the [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) spec**. If the xpub is associated with an account in an HD bitcoin wallet, do not expect the wallet to continue to work as expected, as most HD wallets will follow BIP44. **This includes Blockchain Wallet and Blockchain Wallet Service!** Proceed at your own risk, you will likely have to figure out how to manually create transactions to spend from addresses beyond where the expected 20 address limit is exceeded. Balance and transaction lookups for these addresses **will not work** on the blockchain.info explorer.

**It is recommended to use methods described previously in this thread that keep the gap limit below 20 before resorting to raising the gap limit.**

**Comment by JustPerfection** [comment] 2018-05-22 22:13
Increasing gap limit is not a good solution as I explained before.

You know much better than me, maybe we need a method to say to the wallet to do not look at specific address after the invoice expired. maybe we can have another option like expire time.

**Comment by jtormey** [comment] 2018-05-23 18:17
There doesn't seem to be a perfect solution. I don't think we will add an "expire time" option, since that opens the door to address reuse, which could compromise privacy.

That doesn't mean you can't implement it yourself though, as explained in the Stack Exchange link you posted. In practice, expiry time may work if you set it to a sufficiently long period of time (48h?). And maybe use a "pool" of xpubs such that you don't run out of addresses too quickly.

**Comment by jtormey** [comment] 2018-05-23 18:19
The root of the issue is that BIP44 is a standard meant for wallets, not payment platforms. Having 20 consecutive unused addresses is rare for wallets, whereas not so much for payment platforms.

We blur this line with the Receive Payments API because doing so means we can provide this service without having custody over funds. Part of our philosophy is to give users complete control over their own funds, and unfortunately this sometimes comes with inconveniences that custodial platforms don't have.

**Comment by enriquepiatti** [comment] 2019-06-02 04:22
How is counted the gap limit? it must be 20 **consecutive** not used addresses?    
I mean if 5 to 25 address are not used (gap = 20), and someone (or we) use the 22 address, the gap is now 3 or 19?

**Comment by jtormey** [comment] 2019-06-03 14:07
In your example, the gap would be 3.

The allowed address gap is 20 unused addresses beyond the last used address. So, in theory you could skip 19 addresses between every time you receive.

If you receive funds to an address that's past the gap limit, you can extend your address gap by sending some funds within the gap limit. This can be repeated until you reach the address that was past your current gap limit.

**Comment by MAJARS** [comment] 2019-06-03 17:27
U can't but a baker's man can ....chocolate with a token to come after
Global coin🗣

**Comment by Mikki21** [comment] 2019-09-19 11:50
Hello, if I recieve first transaction on generated address can i get another transaction on it? Or it won be able to recieve txs anymore?
